name: Docker Image Build and Publish

on:
  push:
    branches:
      - main
      - docker-autobuild

jobs:
  build-and-push-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          shortSHA=$(git rev-parse --short ${{ github.sha }})
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$shortSHA
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker image tag ghcr.io/${{ github.repository }}:$shortSHA ghcr.io/${{ github.repository }}:latest
          else
            docker image tag ghcr.io/${{ github.repository }}:$shortSHA ghcr.io/${{ github.repository }}:test
          fi
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }} --all-tags
